services:
  postgres:
    image: postgres:16
    container_name: dataroom-postgres
    environment:
      POSTGRES_DB: dataroom
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d dataroom"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
